# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'sso://cpdc-internal/spec'
source 'sso://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'text-recognition' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for text-recognition
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'
  
end
